trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# Once caching of vcpkg exists this will allow us to test the gui build
# - script: vcpkg install qt5-base
#   displayName: 'Install qt5'

- script: sudo apt update && sudo apt install qt5-default
  displayName: 'Install qt5'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
  displayName: 'CMake'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'
  displayName: 'Build'
