strategy:
  matrix:
    # Ubuntu
    Ubuntu:
      imageName: 'ubuntu-16.04'
      buildGui: 'ON'
      specificCompiler: 'g++-8'
    # macOS - turn on when we can get filesystem working with macOS
#    macOS:
#      imageName: 'macOS-10.14'
#      buildGui: 'OFF'
    # Windows
    Windows:
      imageName: 'vs2017-win2016'
      buildGui: 'OFF'

pool:
  vmImage: $(imageName)

steps:

# Once caching of vcpkg exists this will allow us to test the gui build
# - script: vcpkg install qt5-base
#   displayName: 'Install qt5'

- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt update
    sudo apt install qt5-default g++-8 libopenslide-dev
#    sudo apt install clang++-8 clang-tidy-8
    export CXX=g++-8
  displayName: 'Install dependencies Ubuntu'
  condition: startsWith(variables['imageName'], 'ubuntu')

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '.. -DSlideSight_BUILD_GUI:BOOL=$(buildGui) -DCMAKE_CXX_COMPILER=$(specificCompiler)'
  displayName: 'CMake'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'
  displayName: 'Build'

- script: ctest -V
  displayName: 'Test'
  workingDirectory: 'build'
