strategy:
  matrix:
    # Ubuntu
    Ubuntu:
      imageName: 'ubuntu-16.04'
      buildGui: 'ON'
    # macOS
    macOS:
      imageName: 'macOS-10.14'
      buildGui: 'OFF'
    # Windows
    Windows:
      imageName: 'vs2017-win2016'
      buildGui: 'OFF'

pool:
  vmImage: $(imageName)

steps:

# Once caching of vcpkg exists this will allow us to test the gui build
# - script: vcpkg install qt5-base
#   displayName: 'Install qt5'

- script: sudo apt update && sudo apt install qt5-default
  displayName: 'Install qt5'
  condition: eq(variables['buildGui'], 'ON')

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '.. -DSlideSight_BUILD_GUI:BOOL=$(buildGui)'
  displayName: 'CMake'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'
  displayName: 'Build'

- script: ctest -V
  displayName: 'Test'
  workingDirectory: 'build'