# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    vcpkg version
    vcpkg search qt5
  displayName: 'vcpkg'

# - script: vcpkg install qt5-base
#   displayName: 'Install qt5'

- script: sudo apt install qt5-default
  displayName: 'Install qt5'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
  displayName: 'CMake'

# - script: |
#     mkdir build && cd build
#     cmake ..
#   displayName: 'CMake'

# - script: |
#     cmake .. --build
#   displayName: 'Build'